### ISSUE TITLE
Akeneo Ubuntu 18.04 request.CRITICAL: Uncaught PHP Exception

### ISSUE THREAD

**Issue by alexpebody** [akeneo/pim-docs#1621]
Could anybody help please? Installed Akeneo by this listing: https://websiteforstudents.com/install-akeneo-pim-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-and-php-7-1-support/

Was not worked DB connection, i solved it, need correct config in: /var/www/html/akeneo/pim-community-standard/app/config/parameters.yml

I installed elasticsearch and set for localhost and port 9200

**But i still get this critical error, i can't found any solution in google all advices not working. Need help please?**

All right is 755 and chown www-data, mysql DB working, elasticsearch too.

```
[2021-04-26 19:47:43] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist" at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 107 {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2021-04-26 19:47:43] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 107) {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
[2021-04-26 19:47:43] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist" at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 107 {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akeneo_pim.pim_session' doesn't exist at /var/www/html/akeneo/pim-community-standard/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```

**Comment by alexpebody** [comment]
i searched for akeneo_pim.pim_session - all solves not working from google. like this:

https://github.com/akeneo/pim-community-dev/issues/7196 
and 
https://github.com/akeneo/pim-community-dev/issues/9314

all advices was do and nothink.

chown -R www-data:www-data /var/lib/php/sessions and chmod -R 777 /var/lib/php/sessions and chown -R nobody:nogroup /var/lib/php/sessions/

not result too

**Comment by Doodoune** [comment]
Hi @alexpebody!

The documentation that you follow will not work for the last version of the PIM. 
For example, in our last version (5.0), your environment has to follow the system requirements (so PHP 7.4, MySQL 8.0.22 etc.)
https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html

Your error says that the table "akeneo_pim.pim_session" doesn't exist in your database.
Did you try to just install the database?
Depending on your PIM version, the command is not the same, but you could search it with this command:
`bin/console | grep db`

Hope it will help you.
Best regards,
Elodie

**Comment by alexpebody** [comment]
Thank you for reply, yes sure DB was added:
```
CREATE DATABASE akeneo_pim;
Create a database user called akeneo_pim with new password
CREATE USER 'akeneo_pim'@'localhost' IDENTIFIED BY 'akeneo_pim';
Then grant the user full access to the database.
GRANT ALL ON akeneo.* TO 'akeneo_pim'@'localhost' IDENTIFIED BY 'akeneo_pim' WITH GRANT OPTION;
Finally, save your changes and exit
FLUSH PRIVILEGES;
EXIT;
```

and file /var/www/html/akeneo/pim-community-standard/app/config/parameters.yml has:
```
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: akeneo_pim
    database_user: akeneo_pim
    database_password: akeneo_pim
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: 'localhost: 9200'
```

and result bin/console | grep db:
```
root@akeneo:~# cd /var/www/html/akeneo/pim-community-standard
root@akeneo:/var/www/html/akeneo/pim-community-standard# bin/console | grep db
  pim:installer:db                                     Prepare database and load fixtures
```

**Comment by Doodoune** [comment]
The DB was "created" but not "populated".
Try to execute the command `bin/console pim:installer:db`, it will populate your database.

**Comment by alexpebody** [comment]
Ok here is, so thx for help! 8-)

bin/console pim:installer:db (many errors):
```
root@akeneo:/var/www/html/akeneo/pim-community-standard# bin/console pim:installer:db
Prepare database schema
Dropped database for connection named `akeneo_pim`
Created database `akeneo_pim` for connection named default
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
07:25:21 ERROR     [console] Error thrown while running command "doctrine:schema:create --no-debug=1 --env=dev". Message: "Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE pim_catalog_product_model (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updated DATETIME NOT NULL COMMENT '(DC2Type:datetime)', root INT NOT NULL, lvl INT NOT NULL, lft 

many errors... ((

```

**Comment by alexpebody** [comment]
Maybe need del DB and create new?

**Comment by alexpebody** [comment]
/var/www/html/akeneo/pim-community-standard/app/config/parameters.yml.dist is:
```
parameters:
    database_driver:                      pdo_mysql
    database_host:                        localhost
    database_port:                        3306
    database_name:                        akeneo_pim
    database_user:                        akeneo_pim
    database_password:                    akeneo_pim
    locale:                               en
    secret:                               ThisTokenIsNotSoSecretChangeIt
    product_index_name:                   akeneo_pim_product
    product_model_index_name:             akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts:                          'localhost: 9200'

```

**Comment by alexpebody** [comment]
**Sad but i tried dell BD and create new and set root rights and check access and nothing! 8-( The same issues, can't crreate some tables...**

**Comment by Doodoune** [comment]
It's because you use MariaDB. We don't support it and it's normal to have this kind of issue. 

We only support MySQL (cf system requirements of 5.0 - https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html)

I strongly encourage you to follow our official documentation to install the PIM: https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1804.html

Best regards,
Elodie

**Comment by alexpebody** [comment]
So thx! Ive try using MySQL DB and reinstall it. Send result here, thx again! 8-)

**Comment by alexpebody** [comment]
Could you tell me please what's mean? Don’t forget to add the web directory of your Symfony application? Where i need set and what? Thank you.

**Comment by Doodoune** [comment]
Could you send a screenshot of your issue. Without context it's complicated. :)

**Comment by alexpebody** [comment]
Sure ) https://yadi.sk/i/qmMQEyjzjZaQMg

**Comment by alexpebody** [comment]
End of document https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1804.html? But how install Akeneo? Just unpack archive? How version need take on Ubuntu 18.04? End of doc and no any about install?

**Comment by Doodoune** [comment]
I don't see any picture on your URL.

See this documentation for the Community Edition: https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html

**Comment by alexpebody** [comment]
Copy and open in Browser new tag https://yadi.sk/i/qmMQEyjzjZaQMg

**Comment by alexpebody** [comment]
https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html - this is for docker... ( all config inside for docker...

what version compatible with Ubuntu 18.04? like this Installation: https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_1804.html

strange why not installation instruction...

**Comment by alexpebody** [comment]
OMG cant understand... i reinstalled 12 times Akeneo ((( and cant install normally... So sad for me!

If i will install like this Installation: https://websiteforstudents.com/install-akeneo-pim-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-and-php-7-1-support/

But using MySql will be ok? I cant understand how install other way (( maybe i am stupid...

**Comment by alexpebody** [comment]
Good day. Elodie Doodoune pelase help a little... I am thinking right?
a step: After install: https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_install_ubuntu_2004.html
b step: I must going that: https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html

c step: composer create-project akeneo/pim-community-standard /srv/pim "5.0.*@stable" - i need install docker? Or this install without docker? Because back step (a step) i was install all component for Akeneo right, i can't understand what must i do after a step? exactly?

thank you!

**Comment by alexpebody** [comment]
About trying install with Docker (command run as root why perm denied?):
```
root@akeneo:~# docker run -u www-data -v $(pwd):/srv/pim -w /srv/pim --rm akeneo/pim-php-dev:4.0 \
>     php -d memory_limit=4G /usr/local/bin/composer create-project --prefer-dist \
>     akeneo/pim-community-standard /srv/pim "4.0.*@stable"
Unable to find image 'akeneo/pim-php-dev:4.0' locally
4.0: Pulling from akeneo/pim-php-dev
f7ec5a41d630: Pull complete
2aa8a277c591: Pull complete
b936e17abd5e: Pull complete
5380cd2ac9cc: Pull complete
98ebdab1e627: Pull complete
f7b7b2d9fecf: Pull complete
f707f2523a57: Pull complete
ae6b33d089e4: Pull complete
5f574dab1016: Pull complete
dc140871fbd1: Pull complete
8c4927ce3d39: Pull complete
Digest: sha256:3fefb65aa516b63120feffdbbc1aca05bd03c79841a23b37f9cba861e87994f5
Status: Downloaded newer image for akeneo/pim-php-dev:4.0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/srv/pim") set in config.json failed: permission denied: unknown.
```

**Comment by alexpebody** [comment]
I had tried install this way, how solved this issue? I can't install Akeneo!

Got error:
```
root@akeneo:/var/www/akeneo/pim-community-standard# bin/console pim:install --force --symlink --clean --env=prod
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/akeneo/pim-community-standard/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/akeneo/pim-community-standard/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665

In ApcuCache.php line 44:

  Call to undefined function Doctrine\Common\Cache\apcu_exists()


pim:install [--force] [--symlink] [--clean] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by Doodoune** [comment]
* **If you use docker**, please follow this documentation: https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html
* **If you don't use docker**, first be sure that you have an environment that **follows the system requirements** (in your error it says that you don't enable APCU locally - it's required in our system requirements) - https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html
THEN follow this documentation - https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html it doesn't use docker to install it.
Normally you should not have an error during the launch of the command `NO_DOCKER=true make dev`, if you have one, please put the full error message here.

**Comment by alexpebody** [comment]
Elodie could you please help just one issue and finish, with docker i will trying later, now i need solved just one problem, i installed Akeneo like this manual: https://webkul.com/blog/setup-akeneo2-php7/ this is 12 or 15 try... and again fall 8-(

I create new virtual pc in cloud, then step by step install it and got issue about imagemagick, ok i had install imagemagick and check it: php -m | grep imagick and got result - imagick, was installed, but next try:  bin/console pim:install --force --symlink --clean --env=prod for populate DB i got next error: Call to undefined function Doctrine\Common\Cache\apcu_exists() but apcu is installed - new error:

In PDOConnection.php line 86:

  Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(str
  ing $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

**Comment by alexpebody** [comment]
done. so thx!

```
---------------------------------------------------------------------------------------+
| OK      | Vendors should be installed in order to check all requirements.                                                                                                                                                                           |
| OK      | Requirements file should be up-to-date                                                                                                                                                                                                    |
| OK      | You should use at least PHP 5.3.4 due to PHP bug #52083 in earlier versions                                                                                                                                                               |
| OK      | When using annotations you should have at least PHP 5.3.8 due to PHP bug #55156                                                                                                                                                           |
| OK      | You should not use PHP 5.4.0 due to the PHP bug #61453                                                                                                                                                                                    |
| OK      | When using the logout handler from the Symfony Security Component, you should have at least PHP 5.4.11 due to PHP bug #63379 (as a workaround, you can also set invalidate_session to false in the security logout handler configuration) |
| OK      | You should use PHP 5.3.18+ or PHP 5.4.8+ to always get nice error messages for fatal errors in the development environment due to PHP bug #61767/#60909                                                                                   |
| OK      | PCRE extension should be at least version 8.0 (8.44 installed)                                                                                                                                                                            |
| OK      | PHP-DOM and PHP-XML modules should be installed                                                                                                                                                                                           |
| OK      | mb_strlen() should be available                                                                                                                                                                                                           |
| OK      | utf8_decode() should be available                                                                                                                                                                                                         |
| OK      | filter_var() should be available                                                                                                                                                                                                          |
| OK      | posix_isatty() should be available                                                                                                                                                                                                        |
| OK      | intl extension should be available                                                                                                                                                                                                        |
| OK      | intl extension should be correctly configured                                                                                                                                                                                             |
| OK      | intl ICU version should be at least 4+                                                                                                                                                                                                    |
| OK      | intl ICU version installed on your system is outdated (65.1) and does not match the ICU data bundled with Symfony (60.1)                                                                                                                  |
| WARNING | To avoid internationalization data inconsistencies upgrade the symfony/intl component.                                                                                                                                                    |
| OK      | intl.error_level should be 0 in php.ini                                                                                                                                                                                                   |
| OK      | a PHP accelerator should be installed                                                                                                                                                                                                     |
| OK      | short_open_tag should be disabled in php.ini                                                                                                                                                                                              |
| OK      | magic_quotes_gpc should be disabled in php.ini                                                                                                                                                                                            |
| OK      | register_globals should be disabled in php.ini                                                                                                                                                                                            |
| OK      | session.auto_start should be disabled in php.ini                                                                                                                                                                                          |
| OK      | PDO should be installed                                                                                                                                                                                                                   |
| OK      | PDO should have some drivers installed (currently available: mysql)                                                                                                                                                                       |
| OK      | cURL extension must be at least 7.0                                                                                                                                                                                                       |
| WARNING | Set apc.enable_cli to 1                                                                                                                                                                                                                   |
+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Prepare database schema
Dropped database for connection named `akeneo_pim`
Created database `akeneo_pim` for connection named default
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...

```

**Comment by alexpebody** [comment]
but still on web access is: **HTTP ERROR 500**

`PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/ConvertProductToVariantProduct.php:22\nStack trace:\n#0 /var/www/akeneo/pim-community-standard/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/akeneo...')\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Pim\\\\Bundle\\\\Cata...')\n#2 /var/www/akeneo/pim-community-standard/var/cache/prod/ContainerTcbsszt/appProdProjectContainer.php(5662): spl_autoload_call('Pim\\\\Bundle\\\\Cata...')\n#3 /var/www/akeneo/pim-community-standard/var/cache/prod/ContainerTcbsszt/appProdProjectContainer.php(5672): ContainerTcbsszt\\appProdProjectContainer->getPimCatalog_Doctrine_Query_ConvertProductToVariantProductService()\n#4 /var/www/akeneo/pim-community-standard/var/cache/prod/ContainerTcbsszt/appProdProjectContainer.php(4984 in /var/www/akeneo/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/ConvertProductToVariantProduct.php on line 22`

But all DB was created and populated well, and yarn run webpack is ok. look below:

```
root@akeneo:/var/www/akeneo/pim-community-standard# yarn run webpack
yarn run v1.22.5
warning package.json: No license field
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
Starting webpack from /var/www/akeneo/pim-community-standard in prod mode

WebpackCleanupPlugin: 0 file(s) deleted.
Version: webpack 3.5.5
Time: 25224ms
              Asset     Size  Chunks                    Chunk Names
        main.min.js  2.03 MB       0  [emitted]  [big]  main
         lib.min.js     1 MB       1  [emitted]  [big]  lib
      vendor.min.js  1.07 kB       2  [emitted]         vendor
    manifest.min.js  5.88 kB       3  [emitted]         manifest
    main.min.js.map  2.49 MB       0  [emitted]         main
     lib.min.js.map  1.18 MB       1  [emitted]         lib
  vendor.min.js.map  1.37 kB       2  [emitted]         vendor
manifest.min.js.map  5.98 kB       3  [emitted]         manifest
```

```
Prepare database schema
Dropped database for connection named `akeneo_pim`
Created database `akeneo_pim` for connection named default
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!
Nothing to update - your database is already in sync with the current entity metadata.
Reset elasticsearch indexes
Create session table
Load jobs for fixtures. (data set: PimInstallerBundle:icecat_demo_dev)
Fixtures fixtures_currency_csv has been successfully executed.
Fixtures fixtures_locale_csv has been successfully executed.
Fixtures fixtures_user_group_csv has been successfully executed.
Fixtures fixtures_category_csv has been successfully executed.
Fixtures fixtures_attribute_group_csv has been successfully executed.
Fixtures fixtures_group_type_csv has been successfully executed.
Fixtures fixtures_attribute_csv has been successfully executed.
Fixtures fixtures_channel_csv has been successfully executed.
Fixtures fixtures_association_type_csv has been successfully executed.
Fixtures fixtures_attribute_options_csv has been successfully executed.
Fixtures fixtures_family_csv has been successfully executed.
Fixtures fixtures_job_yml has been successfully executed.
Fixtures fixtures_family_variant_csv has been successfully executed.
Fixtures fixtures_group_csv has been successfully executed.
Fixtures fixtures_user_role_csv has been successfully executed.
Fixtures fixtures_user_csv has been successfully executed.
Fixtures fixtures_product_model_csv has been successfully executed.
Fixtures fixtures_product_csv has been successfully executed.

Delete jobs for fixtures.
Versioning is already up to date.
Akeneo PIM assets
Dumping exposed routes.

[file+] /var/www/akeneo/pim-community-standard/app/../web/js/routes.js

 Installing assets as hard copies.

 --- ------------------------------------------------------------------------ ---------------- 
      Bundle                                                                   Method / Error  
 --- ------------------------------------------------------------------------ ---------------- 
  ✔   FOSJsRoutingBundle                                                       copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/fosjsrouting                       
  ✔   OroAsseticBundle                                                         copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/oroassetic                         
  ✔   OroConfigBundle                                                          copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/oroconfig                          
  ✔   PimNavigationBundle                                                      copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimnavigation                      
  ✔   PimUserBundle                                                            copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimuser                            
  ✔   PimAnalyticsBundle                                                       copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimanalytics                       
  ✔   PimDashboardBundle                                                       copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimdashboard                       
  ✔   PimDataGridBundle                                                        copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimdatagrid                        
  ✔   PimEnrichBundle                                                          copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimenrich                          
  ✔   PimImportExportBundle                                                    copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimimportexport                    
  ✔   PimNotificationBundle                                                    copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimnotification                    
  ✔   PimReferenceDataBundle                                                   copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimreferencedata                   
  ✔   PimUIBundle                                                              copy            
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimui                              
 --- ------------------------------------------------------------------------ ---------------- 

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.  

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        

Dumping all prod assets.
Debug mode is off.

Dumping all prod assets.
Debug mode is off.

17:37:46 [file+] /var/www/akeneo/pim-community-standard/app/../web/css/pim.css
Generating require.js main config
17:37:47 [file+] en.js
17:37:47 [file+] fr.js
17:37:47 [file+] nl.js
17:37:47 [file+] de.js
17:37:47 [file+] ru.js
17:37:47 [file+] ja.js
17:37:47 [file+] pt.js
17:37:47 [file+] it.js

 Trying to install assets as relative symbolic links.

 --- ------------------------------------------------------------------------ ------------------ 
      Bundle                                                                   Method / Error    
 --- ------------------------------------------------------------------------ ------------------ 
  ✔   FOSJsRoutingBundle                                                       relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/fosjsrouting                         
  ✔   OroAsseticBundle                                                         relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/oroassetic                           
  ✔   OroConfigBundle                                                          relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/oroconfig                            
  ✔   PimNavigationBundle                                                      relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimnavigation                        
  ✔   PimUserBundle                                                            relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimuser                              
  ✔   PimAnalyticsBundle                                                       relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimanalytics                         
  ✔   PimDashboardBundle                                                       relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimdashboard                         
  ✔   PimDataGridBundle                                                        relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimdatagrid                          
  ✔   PimEnrichBundle                                                          relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimenrich                            
  ✔   PimImportExportBundle                                                    relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimimportexport                      
  ✔   PimNotificationBundle                                                    relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimnotification                      
  ✔   PimReferenceDataBundle                                                   relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimreferencedata                     
  ✔   PimUIBundle                                                              relative symlink  
      -> /var/www/akeneo/pim-community-standard/web/bundles/pimui                                
 --- ------------------------------------------------------------------------ ------------------ 

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        


Akeneo PIM Application has been successfully installed.
```

**Comment by VivekShingala** [comment]
> * **If you use docker**, please follow this documentation: https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html
> * **If you don't use docker**, first be sure that you have an environment that **follows the system requirements** (in your error it says that you don't enable APCU locally - it's required in our system requirements) - https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html
>   THEN follow this documentation - https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html it doesn't use docker to install it.
>   Normally you should not have an error during the launch of the command `NO_DOCKER=true make dev`, if you have one, please put the full error message here.

Hello, I don't have any error in NO_DOCKER command but still can't access the PIM. What should be the document root?
